easy_admin:
    entities:
        # List the entity class name you want to manage
        Site:
            class: App\Entity\Site
        User:
            class: App\Entity\User
            form:
                fields:
                    - 'email'
                    - 'username'
                    - 'isActive'
                    - { property: 'roles', type: 'choice', type_options: { multiple: true, choices: { 'ROLE_USER': 'ROLE_USER', 'ROLE_ADMIN': 'ROLE_ADMIN', 'ROLE_SUPER_ADMIN': 'ROLE_SUPER_ADMIN' } } }