enqueue:
    transport:
        default: redis
        redis:
            dsn: "redis://%env(REDIS_HOST)%:%env(REDIS_PORT)%?vendor=predis&password=%env(REDIS_PASSWORD)%"
            #dsn: "redis://%env(REDIS_HOST)%:%env(REDIS_PORT)%" # no password
            vendor: predis
    client:
        prefix: enqueue
        app_name: gr
        router_queue: default
        default_processor_queue: default