enqueue:
    transport:
        default: redis
        redis:
            dsn: "redis://%env(REDIS_HOST)%:%env(REDIS_PORT)%" # no password
            vendor: predis
    client:
        prefix: cust_report
        app_name: cust_app
        router_queue: cust
        default_processor_queue: cust