framework:
    secret: '%env(APP_SECRET)%'
    default_locale: en
    #csrf_protection: ~
    #http_method_override: true

    #esi: ~
    #fragments: ~
    php_errors:
        log: true

    session:
        handler_id: app.infrastructure.session.redis

    assets:
        json_manifest_path: '%kernel.project_dir%/public/build/manifest.json'
        base_urls:
            - '%env(ASSET_STATIC_URL_PROTOCOL)%%env(ASSET_STATIC_URL)%'