security:
    encoders:
        App\Entity\User:
            algorithm: bcrypt
            cost: 12

    providers:
        doctrine:
            entity:
                class: App\Entity\User

    firewalls:
        main:
            pattern:    ^/
            anonymous: ~
            http_basic: ~
            provider: doctrine
            form_login:
                login_path: login
                check_path: login
            logout:
                path:   /logout
                target: /

    access_control:
        - { path: ^/login, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/account, roles: ROLE_USER }
        - { path: ^/admin, roles: ROLE_ADMIN }
        - { path: ^/admin/users, roles: ROLE_SUPER_ADMIN }
        - { path: ^/, roles: IS_AUTHENTICATED_ANONYMOUSLY }

    role_hierarchy:
        ROLE_ADMIN:       ROLE_USER
        ROLE_SUPER_ADMIN:       ROLE_ADMIN