# Project language
language: php

# Allows use container-based infrastructure
sudo: false

# Start mysql service
services:
  - mysql
  - redis-server

php:
  - 7.2
  #- master

# Env
env:
  matrix:
    - DEPENDENCIES="high"
    #- DEPENDENCIES="low"
  global:
    - DEFAULT_COMPOSER_FLAGS="--no-interaction --no-ansi --no-progress --no-suggest"

# Host (https://docs.travis-ci.com/user/hosts)
addons:
  hosts:
    - getresources.local

# Cache composer packages so "composer install" is faster
cache:
  directories:
    - $HOME/.composer/cache/files

# Update composer
before-install:
  - composer self-update
  - composer clear-cache

# Install
install:
  - if [[ "$DEPENDENCIES" = 'high' ]]; then travis_retry composer update $DEFAULT_COMPOSER_FLAGS; fi
  - if [[ "$DEPENDENCIES" = 'low' ]]; then travis_retry composer update $DEFAULT_COMPOSER_FLAGS --prefer-lowest; fi

before_script:
  - echo `pwd`
  - mysql -u root -e 'CREATE DATABASE ${DATABASE_DB};'
  - php bin/console doctrine:schema:create
  - php bin/console doctrine:schema:validate

# Run script
script:
  - php bin/phpunit --coverage-clover=coverage.xml

after_success:
  - bash <(curl -s https://codecov.io/bash)

# After a build, send email notification with the build results
notifications:
  email: hello@getresources.tech