enqueue:
    transport:
        default: redis
        redis:
            dsn: "redis://%env(REDIS_ENDPOINT)%:%env(REDIS_PORT)%?vendor=predis&password=%env(REDIS_PASSWORD)%"
            vendor: predis