monolog:
    handlers:
        main:
            type: fingers_crossed
            action_level: error
            handler: file_handler
            excluded_404s:
                # regex: exclude all 404 errors from the logs
                - ^/
        file_handler:
            type: rotating_file
            path: "%kernel.logs_dir%/%kernel.environment%.log"
            level: debug
            max_files: 10

        console:
            type:   console
            process_psr_3_messages: false
            channels: ["!event", "!doctrine"]

        syslog_handler:
            type: syslog
            # log error-level messages and higher
            level: error
