-- Doctrine Migration File Generated on 2018-01-07 18:05:07

-- Version 20180107170502
ALTER TABLE language ADD created_by_id CHAR(36) DEFAULT NULL COMMENT '(DC2Type:guid)', ADD site_id CHAR(36) NOT NULL COMMENT '(DC2Type:guid)', ADD name INT NOT NULL, ADD created DATETIME NOT NULL, CHANGE id id CHAR(36) NOT NULL COMMENT '(DC2Type:guid)';
ALTER TABLE language ADD CONSTRAINT FK_D4DB71B5B03A8386 FOREIGN KEY (created_by_id) REFERENCES user (id);
ALTER TABLE language ADD CONSTRAINT FK_D4DB71B5F6BD1646 FOREIGN KEY (site_id) REFERENCES site (id);
CREATE INDEX IDX_D4DB71B5B03A8386 ON language (created_by_id);
CREATE INDEX IDX_D4DB71B5F6BD1646 ON language (site_id);
ALTER TABLE site ADD is_highlight TINYINT(1) DEFAULT '0', CHANGE author author VARCHAR(255) DEFAULT NULL, CHANGE author_url author_url VARCHAR(255) DEFAULT NULL, CHANGE rate rate INT DEFAULT NULL, CHANGE hit hit INT DEFAULT NULL, CHANGE is_validated is_validated TINYINT(1) DEFAULT '0';
ALTER TABLE source ADD created_by_id CHAR(36) DEFAULT NULL COMMENT '(DC2Type:guid)', ADD site_id CHAR(36) NOT NULL COMMENT '(DC2Type:guid)', ADD name INT NOT NULL, ADD created DATETIME NOT NULL, CHANGE id id CHAR(36) NOT NULL COMMENT '(DC2Type:guid)';
ALTER TABLE source ADD CONSTRAINT FK_5F8A7F73B03A8386 FOREIGN KEY (created_by_id) REFERENCES user (id);
ALTER TABLE source ADD CONSTRAINT FK_5F8A7F73F6BD1646 FOREIGN KEY (site_id) REFERENCES site (id);
CREATE INDEX IDX_5F8A7F73B03A8386 ON source (created_by_id);
CREATE INDEX IDX_5F8A7F73F6BD1646 ON source (site_id);
ALTER TABLE user CHANGE email email VARCHAR(255) DEFAULT NULL;
INSERT INTO migration_versions (version) VALUES ('20180107170502');
